services:
  - type: web
    name: eiskenproperties
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:Io4CJtZhlrD3aCxE1oO5NwtKuCujppEFTjJ+MyVgx1U=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-eu-west-2.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.bbxtbqstyfhfjybywyya
      - key: DB_PASSWORD
        value: DotSeek_EiskenDB@2025
